name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Fix Style
        run: ./vendor/bin/pint -v

      - name: pwsh
        shell: pwsh
        id: random-color-generator
        run: |
          $isDiff = (git diff).Length -gt 0
          echo "SELECTED_COLOR=$isDiff" >> $env:GITHUB_OUTPUT

      - name: Get color
        run: echo "${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - name: Commit report
        if: ${{ steps.random-color-generator.outputs.SELECTED_COLOR == 'True' }}
        run: |
          git config --local user.name "$(git log -n 1 --pretty=format:%an)"
          git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -am "Commit report"
          git push
