name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Fix Style
        run: ./vendor/bin/pint -v

      - name: pwsh
        shell: pwsh
        id: random-color-generator
        run: |
          $diff = git diff
          $isDiff = $diff.Length -gt 0
          echo "SELECTED_COLOR=True" >> $env:GITHUB_OUTPUT

      - name: Get color
        run: echo "${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - name: Commit report
        if: ${{ steps.random-color-generator.outputs.SELECTED_COLOR == 'True' }}
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Commit report"
          git push
